eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka/
            
---            
spring:
  profiles: lab-4-subject-1
words: I,You,He,She,It

---
spring:
  profiles: lab-4-subject
words: ran,knew,had,saw,bought

